// Builds the "dist" folder that Netlify publishes.
// Run with:  node build.js
//
// dist/index.html            the Passive Array home page (generated by creator-tools/build-tools.js)
// dist/<tool>/index.html     each web tool's page, copied from its folder
// dist/creator-tools/        the tools directory and the 35 creator tool pages
// dist/favicon.*, og-image   brand files copied from passive-array-brand/
//
// Server code stays private; the Netlify Functions in netlify/functions provide the /api routes.
// To add a web tool, add a line to TOOLS below and to WEB_TOOLS in creator-tools/build-tools.js.

const fs = require("fs");
const path = require("path");

// folder name -> path of the page to publish (relative to that folder)
const TOOLS = {
  "domain-finder": "public/index.html",
  "domain-age-checker": "index.html",
  "plagiarism-checker": "index.html",
  "jpg-to-pdf": "index.html",
  "seo-roi-calculator": "index.html",
};

const ROOT = __dirname;
const DIST = path.join(ROOT, "dist");

// Required up here because withSiteChrome() below uses it while copying the web tools.
const site = require("./creator-tools/build-tools.js");

fs.rmSync(DIST, { recursive: true, force: true });
fs.mkdirSync(DIST, { recursive: true });

for (const [folder, page] of Object.entries(TOOLS)) {
  const src = path.join(ROOT, folder, page);
  if (!fs.existsSync(src)) {
    console.error("MISSING: " + src);
    process.exit(1);
  }
  const outDir = path.join(DIST, folder);
  fs.mkdirSync(outDir, { recursive: true });
  fs.writeFileSync(path.join(outDir, "index.html"), withWebGuide(withSiteChrome(fs.readFileSync(src, "utf8")), folder));
  console.log(folder + "/" + page + " -> dist/" + folder + "/index.html (+ site bar and footer)");
}

// The web tools are self-contained pages with their own styles. Give each one the
// site's navigation bar and footer without loading the shared stylesheet, so their
// own layouts stay untouched. Inserted right after <body> and before </body>.
function withSiteChrome(html) {
  const mark = `<svg viewBox="0 0 120 120" width="26" height="26" aria-hidden="true"><defs><linearGradient id="pabar-g" gradientUnits="userSpaceOnUse" x1="7" y1="7" x2="113" y2="113"><stop offset="0" stop-color="#2A9D8F"/><stop offset="1" stop-color="#5B6ABF"/></linearGradient></defs>${[7, 45, 83].map((y) => [7, 45, 83].map((x) => x === 83 && y === 83 ? `<circle cx="98" cy="98" r="15" fill="#8FD3C7"/>` : `<rect x="${x}" y="${y}" width="30" height="30" rx="7" fill="url(#pabar-g)"/>`).join("")).join("")}</svg>`;
  const style = `<style id="pa-chrome">
.pa-bar{max-width:960px;margin:0 auto 20px;display:flex;align-items:center;gap:14px;padding:10px 14px;border:1px solid rgba(31,42,68,.12);border-radius:14px;background:#fff;font-family:Poppins,system-ui,-apple-system,"Segoe UI",sans-serif;font-size:.92rem}
.pa-bar .pa-brand{display:flex;align-items:center;gap:8px;color:#1F2A44;font-weight:600;text-decoration:none;white-space:nowrap}
.pa-bar .pa-brand b{color:#2A9D8F;font-weight:600}
.pa-bar nav{margin-left:auto;display:flex;flex-wrap:wrap;gap:16px}
.pa-bar nav a{color:#1F2A44;text-decoration:none;font-weight:500}
.pa-bar nav a:hover{color:#1F7F73}
.pa-bar .pa-cta{background:#1F7F73;color:#fff;border-radius:10px;padding:8px 14px;font-weight:600;text-decoration:none;white-space:nowrap}
.pa-foot{max-width:960px;margin:40px auto 0;padding:18px 0 8px;border-top:1px solid rgba(31,42,68,.12);font-family:Poppins,system-ui,-apple-system,"Segoe UI",sans-serif;font-size:.82rem;color:#5A6478;display:flex;flex-wrap:wrap;justify-content:space-between;gap:10px}
.pa-foot nav{display:flex;flex-wrap:wrap;gap:14px}
.pa-foot a{color:#5A6478;text-decoration:none}
.pa-foot a:hover{color:#1F7F73}
@media(max-width:640px){.pa-bar nav{display:none}.pa-bar .pa-cta{margin-left:auto}}
</style>`;
  const bar = `${style}<div class="pa-bar"><a class="pa-brand" href="/">${mark}<span>Passive <b>Array</b></span></a><nav><a href="/creator-tools/">Creator tools</a><a href="/#web-tools">Web tools</a><a href="/youtube-extension/">Extension</a><a href="/blog/">Blog</a></nav><a class="pa-cta" href="/#web-tools">All free tools</a></div>`;
  const foot = `<div class="pa-foot"><span>&copy; ${new Date().getFullYear()} Passive Array. Free tools for creators and brands.</span><nav><a href="/about/">About</a><a href="/blog/">Blog</a><a href="/contact/">Contact</a><a href="/privacy/">Privacy</a><a href="/terms/">Terms</a></nav></div>`;
  if (!/<body[^>]*>/i.test(html) || !/<\/body>/i.test(html)) return html;
  let out = html.replace(/<body([^>]*)>/i, (m) => m + "\n" + (site.GTM_BODY || "") + bar).replace(/<\/body>/i, foot + "\n</body>");
  // Search Console verification tag, same one the generated pages carry.
  if (site.VERIFY_TAG && !out.includes("google-site-verification")) {
    out = out.replace(/<head([^>]*)>/i, (m) => m + "\n" + site.VERIFY_TAG);
  }
  // Analytics, with the same denied-by-default consent as the rest of the site.
  if (site.ANALYTICS_HEAD && !out.includes("PA_ANALYTICS")) {
    out = out.replace(/<head([^>]*)>/i, (m) => m + "\n" + site.ANALYTICS_HEAD);
  }
  return out;
}

// Search title, description, canonical, a long-form guide and an FAQ for each web tool,
// from guides-web/<folder>.js. The web tools do not load the site stylesheet, so the
// guide carries its own small scoped style, matched to the site chrome above.
function withWebGuide(html, folder) {
  const f = path.join(ROOT, "guides-web", folder + ".js");
  if (!fs.existsSync(f)) return html;
  const g = require(f);
  const esc = site.esc;
  const canonical = site.SITE + "/" + folder + "/";
  if (g.seoTitle) html = /<title>[\s\S]*?<\/title>/i.test(html) ? html.replace(/<title>[\s\S]*?<\/title>/i, "<title>" + esc(g.seoTitle) + "</title>") : html.replace(/<head([^>]*)>/i, (m) => m + "\n<title>" + esc(g.seoTitle) + "</title>");
  if (g.seoDescription) {
    html = html.replace(/<meta\s+name="description"[^>]*>\s*/gi, "");
    html = html.replace(/<\/title>/i, "</title>\n<meta name=\"description\" content=\"" + esc(g.seoDescription) + "\">");
  }
  if (!/rel="canonical"/i.test(html)) html = html.replace(/<\/title>/i, "</title>\n<link rel=\"canonical\" href=\"" + canonical + "\">");
  const app = { "@context": "https://schema.org", "@type": "WebApplication", name: (g.seoTitle || folder).split(/[:|]/)[0].trim(), url: canonical, description: g.seoDescription || "", applicationCategory: "UtilitiesApplication", operatingSystem: "Any", offers: { "@type": "Offer", price: "0", priceCurrency: "USD" }, provider: { "@type": "Organization", name: site.BRAND, url: site.SITE } };
  const ld = g.faq && g.faq.length ? [app, site.faqLd(g.faq)] : app;
  html = html.replace(/<\/head>/i, "<script type=\"application/ld+json\">" + JSON.stringify(ld) + "</script>\n</head>");
  const style = `<style id="pa-guide">
.pa-guide{max-width:960px;margin:40px auto 0;padding:32px clamp(18px,4vw,40px);border:1px solid rgba(31,42,68,.12);border-radius:18px;background:#fff;color:#1F2A44;font-family:Poppins,system-ui,-apple-system,"Segoe UI",sans-serif;box-sizing:border-box}
.pa-guide section{max-width:780px}.pa-guide section+section{margin-top:30px;padding-top:26px;border-top:1px solid rgba(31,42,68,.1)}
.pa-guide h2{font-size:1.4rem;line-height:1.25;margin:0 0 12px;color:#1F2A44;letter-spacing:-.01em}
.pa-guide p,.pa-guide li{color:#4A5468;line-height:1.7;font-size:.98rem}.pa-guide p{margin:0 0 12px}
.pa-guide ul,.pa-guide ol{padding-left:22px;margin:0 0 12px}.pa-guide li{margin:4px 0}
.pa-guide b{color:#1F2A44}.pa-guide a{color:#1F7F73}
.pa-guide table{width:100%;border-collapse:collapse;font-size:.92rem;margin:6px 0 14px}.pa-guide th,.pa-guide td{text-align:left;padding:9px 10px;border-bottom:1px solid rgba(31,42,68,.1);vertical-align:top}
.pa-guide .tw{overflow-x:auto}
.pa-guide details{border-top:1px solid rgba(31,42,68,.1);padding:12px 0}.pa-guide details:last-child{border-bottom:1px solid rgba(31,42,68,.1)}
.pa-guide summary{cursor:pointer;font-weight:600;color:#1F2A44}.pa-guide details p{margin-top:8px}
.pa-guide .note{font-size:.82rem;color:#6B7280;margin-top:18px}
</style>`;
  const sec = (s) => `<section><h2>${esc(s.h)}</h2>${(s.p || []).map((p) => `<p>${p}</p>`).join("")}${s.list ? `<${s.ordered ? "ol" : "ul"}>${s.list.map((li) => `<li>${li}</li>`).join("")}</${s.ordered ? "ol" : "ul"}>` : ""}${s.table ? `<div class="tw"><table><thead><tr>${s.table.head.map((h) => `<th>${esc(h)}</th>`).join("")}</tr></thead><tbody>${s.table.rows.map((r) => `<tr>${r.map((c) => `<td>${c}</td>`).join("")}</tr>`).join("")}</tbody></table></div>` : ""}${(s.after || []).map((p) => `<p>${p}</p>`).join("")}</section>`;
  const faq = g.faq && g.faq.length ? `<section><h2>Frequently asked questions</h2>${g.faq.map(([q, a]) => `<details><summary>${esc(q)}</summary><p>${a}</p></details>`).join("")}</section>` : "";
  const others = site.WEB_TOOLS.filter(([href]) => href !== folder + "/").map(([href, name]) => `<a href="/${href}">${esc(name)}</a>`).join(" · ");
  const more = `<section><h2>More free web tools</h2><p>${others}. For creators: <a href="/creator-tools/youtube-monetization-checker/">YouTube monetization checker</a> · <a href="/research/">YouTube keyword research</a>.</p></section>`;
  const block = `${style}<article class="pa-guide">${(g.guide || []).map(sec).join("")}${faq}${more}${g.guideUpdated ? `<p class="note">Checked ${esc(g.guideUpdated)}.</p>` : ""}</article>`;
  return html.replace(/<div class="pa-foot">/, block + "<div class=\"pa-foot\">");
}

// Passive Array pages: home, tools directory and one page per creator tool.
const blog = require("./blog/build-blog.js");
const posts = blog.loadPosts();
fs.writeFileSync(path.join(DIST, "index.html"), site.homePage(posts));
console.log("home page -> dist/index.html (" + site.SITE + ")");
const creatorCount = site.buildInto(path.join(DIST, "creator-tools"), posts);
console.log("creator-tools/tools.js -> dist/creator-tools/ (" + creatorCount + " tool pages + directory)");

// Browser extension pages: landing page and the privacy policy the Chrome Web Store links to.
const ext = require("./youtube-extension/pages.js");
fs.mkdirSync(path.join(DIST, "youtube-extension", "privacy"), { recursive: true });
fs.writeFileSync(path.join(DIST, "youtube-extension", "index.html"), ext.landingPage());
fs.writeFileSync(path.join(DIST, "youtube-extension", "privacy", "index.html"), ext.privacyPage());
console.log("youtube-extension/pages.js -> dist/youtube-extension/ (landing + privacy)");

// Blog: blog/posts/*.md -> dist/blog/ plus one page per category
const built = blog.buildInto(path.join(DIST, "blog"), posts);
console.log("blog/posts/ -> dist/blog/ (" + built.posts + " articles, " + built.categories + " category pages + index)");

// Company pages: about, contact, privacy, terms.
const pages = require("./pages/site-pages.js");
const pagePaths = pages.buildInto(DIST);

// Research: keyword research page (pages/research-pages.js).
const research = require("./pages/research-pages.js");
const researchPaths = research.buildInto(DIST);
console.log("pages/research-pages.js -> dist/ (" + researchPaths.join(", ") + ")");
console.log("pages/site-pages.js -> dist/ (" + pagePaths.all.join(", ") + ")");

// The signed-in dashboard (pages/app-page.js), noindex.
const appPage = require("./pages/app-page.js");
appPage.buildInto(DIST, posts);
pagePaths.noindex.push("/app/");
console.log("pages/app-page.js -> dist/app/");

// sitemap.xml and robots.txt for search engines.
const urls = [
  ["/", "1.0", "weekly"],
  ["/creator-tools/", "0.9", "weekly"],
  ...site.tools.map((t) => ["/creator-tools/" + t.slug + "/", "0.8", "monthly"]),
  ...site.WEB_TOOLS.map(([href]) => ["/" + href, "0.7", "monthly"]),
  ["/research/", "0.8", "weekly"],
  ["/research/outliers/", "0.8", "daily"],
  ["/research/shorts/", "0.7", "daily"],
  ["/youtube-extension/", "0.8", "monthly"],
  ["/youtube-extension/privacy/", "0.3", "yearly"],
  ["/blog/", "0.8", "weekly"],
  ...blog.CATEGORIES.map((c) => ["/blog/category/" + c.slug + "/", "0.7", "weekly"]),
  ...posts.map((p) => ["/blog/" + p.slug + "/", "0.7", "monthly", p.updated]),
  ...pagePaths.indexable.map((p) => [p, p === "/about/" ? "0.5" : "0.3", "yearly"]),
];
const today = new Date().toISOString().slice(0, 10);
// lastmod only moves when a page's own text changes. Each page's main-content text is
// hashed (header, footer, scripts and asset version stamps excluded) and compared with
// sitemap-dates.json, which is committed so Vercel builds see the same dates.
const DATES_FILE = path.join(ROOT, "sitemap-dates.json");
const knownDates = fs.existsSync(DATES_FILE) ? JSON.parse(fs.readFileSync(DATES_FILE, "utf8")) : {};
const nextDates = {};
function contentHash(loc) {
  const f = path.join(DIST, loc, "index.html");
  if (!fs.existsSync(f)) return null;
  let h = fs.readFileSync(f, "utf8");
  h = h.replace(/<script[\s\S]*?<\/script>/gi, " ").replace(/<style[\s\S]*?<\/style>/gi, " ").replace(/<header[\s\S]*?<\/header>/gi, " ").replace(/<footer[\s\S]*?<\/footer>/gi, " ").replace(/<div class="pa-(bar|foot)"[\s\S]*?<\/div>/gi, " ");
  const text = h.replace(/<[^>]+>/g, " ").replace(/\s+/g, " ").trim();
  return require("crypto").createHash("sha1").update(text).digest("hex").slice(0, 16);
}
function lastmodFor(loc, mod) {
  if (mod) return mod;
  const hash = contentHash(loc);
  const prev = knownDates[loc];
  const date = prev && prev.hash === hash ? prev.date : today;
  nextDates[loc] = { hash, date };
  return date;
}
const sitemap = '<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n' +
  urls.map(([loc, pri, freq, mod]) => `  <url><loc>${site.SITE}${loc}</loc><lastmod>${lastmodFor(loc, mod)}</lastmod><changefreq>${freq}</changefreq><priority>${pri}</priority></url>`).join("\n") +
  "\n</urlset>\n";
fs.writeFileSync(path.join(DIST, "sitemap.xml"), sitemap);
try { fs.writeFileSync(DATES_FILE, JSON.stringify(nextDates, null, 1) + "\n"); } catch (_) { /* read-only build host */ }
// Only the API is blocked. Login, sign-up, account and dashboard carry noindex tags,
// which Google can only see if it may crawl them, so they are not disallowed here.
const disallow = ["/api/"].map((p) => "Disallow: " + p).join("\n");
fs.writeFileSync(path.join(DIST, "robots.txt"), "User-agent: *\nAllow: /\n" + disallow + "\n\nSitemap: " + site.SITE + "/sitemap.xml\n");
console.log("sitemap.xml (" + urls.length + " urls) and robots.txt -> dist/");

// Brand files at the site root: favicons, manifest, link preview image.
const brand = path.join(ROOT, "passive-array-brand");
const copies = {
  "favicon/favicon.ico": "favicon.ico",
  "favicon/favicon.svg": "favicon.svg",
  "favicon/apple-touch-icon.png": "apple-touch-icon.png",
  "favicon/icon-192.png": "icon-192.png",
  "favicon/icon-512.png": "icon-512.png",
  "favicon/site.webmanifest": "site.webmanifest",
  "social/og-image-1200x630.png": "og-image-1200x630.png",
  "people/founder-nasir.jpg": "founder-nasir.jpg",
};
let copied = 0;
for (const [from, to] of Object.entries(copies)) {
  const src = path.join(brand, from);
  if (fs.existsSync(src)) {
    fs.copyFileSync(src, path.join(DIST, to));
    copied++;
  }
}
console.log("brand files -> dist/ (" + copied + "/" + Object.keys(copies).length + ")");

// Self-hosted Poppins (assets/fonts) served from /fonts/.
fs.mkdirSync(path.join(DIST, "fonts"), { recursive: true });
for (const f of fs.readdirSync(path.join(ROOT, "assets", "fonts"))) if (f.endsWith(".woff2")) fs.copyFileSync(path.join(ROOT, "assets", "fonts", f), path.join(DIST, "fonts", f));

// IndexNow (Bing, Yandex, Seznam, Naver): the key file must be served at the site root.
// The key is public by design; scripts/indexnow.js submits URLs with it.
const INDEXNOW_KEY = "e3928c4f16234a16a612080c80a35cd8";
fs.writeFileSync(path.join(DIST, INDEXNOW_KEY + ".txt"), INDEXNOW_KEY);


// Cache-busting: every page links shared.css, site.js and shared.js with a
// version derived from their contents, so a new build can never be paired
// with a stylesheet a browser or the CDN cached from the previous one.
const crypto = require("crypto");
const assetVersion = crypto.createHash("md5").update(
  ["shared.css", "site.js", "shared.js", "research.js", "app.js"].map((f) => fs.readFileSync(path.join(ROOT, "creator-tools", "public", f))).join("")
).digest("hex").slice(0, 10);
let stamped = 0;
(function walk(dir) {
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const p = path.join(dir, entry.name);
    if (entry.isDirectory()) { walk(p); continue; }
    if (!entry.name.endsWith(".html")) continue;
    const html = fs.readFileSync(p, "utf8");
    const out = html.replace(/creator-tools\/(shared\.css|site\.js|shared\.js|research\.js|app\.js)"/g, (m, f) => "creator-tools/" + f + "?v=" + assetVersion + "\"");
    if (out !== html) { fs.writeFileSync(p, out); stamped++; }
  }
})(DIST);
console.log("asset version " + assetVersion + " stamped into " + stamped + " pages");
console.log("Build done.");
