// Builds the "dist" folder that Netlify publishes.
// Run with:  node build.js
//
// dist/index.html            the Passive Array home page (generated by creator-tools/build-tools.js)
// dist/<tool>/index.html     each web tool's page, copied from its folder
// dist/creator-tools/        the tools directory and the 35 creator tool pages
// dist/favicon.*, og-image   brand files copied from passive-array-brand/
//
// Server code stays private; the Netlify Functions in netlify/functions provide the /api routes.
// To add a web tool, add a line to TOOLS below and to WEB_TOOLS in creator-tools/build-tools.js.

const fs = require("fs");
const path = require("path");

// folder name -> path of the page to publish (relative to that folder)
const TOOLS = {
  "domain-finder": "public/index.html",
  "domain-age-checker": "index.html",
  "plagiarism-checker": "index.html",
  "jpg-to-pdf": "index.html",
  "seo-roi-calculator": "index.html",
};

const ROOT = __dirname;
const DIST = path.join(ROOT, "dist");

fs.rmSync(DIST, { recursive: true, force: true });
fs.mkdirSync(DIST, { recursive: true });

for (const [folder, page] of Object.entries(TOOLS)) {
  const src = path.join(ROOT, folder, page);
  if (!fs.existsSync(src)) {
    console.error("MISSING: " + src);
    process.exit(1);
  }
  const outDir = path.join(DIST, folder);
  fs.mkdirSync(outDir, { recursive: true });
  fs.copyFileSync(src, path.join(outDir, "index.html"));
  console.log(folder + "/" + page + " -> dist/" + folder + "/index.html");
}

// Passive Array pages: home, tools directory and one page per creator tool.
const site = require("./creator-tools/build-tools.js");
fs.writeFileSync(path.join(DIST, "index.html"), site.homePage());
console.log("home page -> dist/index.html (" + site.SITE + ")");
const creatorCount = site.buildInto(path.join(DIST, "creator-tools"));
console.log("creator-tools/tools.js -> dist/creator-tools/ (" + creatorCount + " tool pages + directory)");

// Browser extension pages: landing page and the privacy policy the Chrome Web Store links to.
const ext = require("./youtube-extension/pages.js");
fs.mkdirSync(path.join(DIST, "youtube-extension", "privacy"), { recursive: true });
fs.writeFileSync(path.join(DIST, "youtube-extension", "index.html"), ext.landingPage());
fs.writeFileSync(path.join(DIST, "youtube-extension", "privacy", "index.html"), ext.privacyPage());
console.log("youtube-extension/pages.js -> dist/youtube-extension/ (landing + privacy)");

// Brand files at the site root: favicons, manifest, link preview image.
const brand = path.join(ROOT, "passive-array-brand");
const copies = {
  "favicon/favicon.ico": "favicon.ico",
  "favicon/favicon.svg": "favicon.svg",
  "favicon/apple-touch-icon.png": "apple-touch-icon.png",
  "favicon/icon-192.png": "icon-192.png",
  "favicon/icon-512.png": "icon-512.png",
  "favicon/site.webmanifest": "site.webmanifest",
  "social/og-image-1200x630.png": "og-image-1200x630.png",
};
let copied = 0;
for (const [from, to] of Object.entries(copies)) {
  const src = path.join(brand, from);
  if (fs.existsSync(src)) {
    fs.copyFileSync(src, path.join(DIST, to));
    copied++;
  }
}
console.log("brand files -> dist/ (" + copied + "/" + Object.keys(copies).length + ")");

console.log("Build done.");
